language: python
python:
  - 2.7
  - 3.5
env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
matrix:
  exclude:
    - python: 3.5
      env: DJANGO=1.6
    - python: 3.5
      env: DJANGO=1.7


install:
  - pip install -q Django==$DJANGO
  - pip install -r dev_requirements.txt
  - python setup.py install
script:
  - coverage run --source=djqscsv test_app/manage.py test djqscsv_tests
  - flake8 --exclude=migrations djqscsv/ test_app/
after_success:
  - coveralls
